Informative UI / Drone Menu
immersive-command-system/ImmersiveDroneInterface_2 pull request #75
Opened 2020-06-23 00:44 UTC by orrblue

This feature adds an informational box to the drone displaying name, location, and drone SDK-control authorization status

2020-06-27 02:25 UTC, PeruDayani commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +        menuCanvas = GameObject.Find("DroneMenuCanvas");
This will be a problem with multiple drones. One way is to simply use GamObjectFindInChildren but there's other better ways to do it too.

2020-06-27 02:25 UTC, PeruDayani commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +        dronePosText = GameObject.Find("DronePos").GetComponent<Text>();
same

2020-06-27 02:26 UTC, PeruDayani commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +        droneNameText = GameObject.Find("DroneName").GetComponent<Text>();
same

2020-06-27 02:26 UTC, PeruDayani commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +        droneAuthorityText = GameObject.Find("DroneAuthority").GetComponent<Text>();
same

2020-06-27 02:27 UTC, PeruDayani commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +        double lat = WorldProperties.UnityXToLat(37.915345, dronePosition.x); // HARDCODED
why is it hardcoded?

2020-06-27 02:28 UTC, PeruDayani commented
One other comment:
Do you think we can generate the UI based on the number of subscribers? 
Like if the user chooses 3 -> we have 3 textboxes constantly updating that info

2020-06-28 20:54 UTC, erwang01 requested changes
Good stuff. Peru's comments requires attention.

2020-06-28 20:54 UTC, erwang01 commented on Assets/Scripts/Menu Scripts/DroneMenu.cs
> +    public Text dronePosText;
commments pls

2020-06-28 20:54 UTC, erwang01 commented on Assets/Scripts/ROS Scripts/ROS Connections v2/ROSManager.cs
> +
remove excess spaces

2020-06-30 14:24 UTC, PeruDayani commented
**These are to be done by @orrblue **
Prefabs:
- [ ] The Canvas will be a child of the drone prefab.
- [ ] DroneMenu will be added to the drone prefab.
- [ ] The Canvas will already be connected to the DroneMenu along with any other text boxes/prefabs needed.

During Runtime:

- [ ] ROSManager will GetCompontent("DroneMenu") and call the custom InitDroneMenu function
- [ ] ROSManager will pass in 2 arguments: ROSDroneInterface rosDroneInterface, List<string> droneSubscribers
- [ ] DroneMenu should generate as many text boxes as len(droneSubscribers)
- [ ] DroneMenu should query the function GetValueOfTopic(string droneSubscriberTopic) for each subscriber and keep updating the UI

**These are to be done by @PeruDayani **
ROSDroneInterface:
- [ ] Add GetValueOfTopic(string droneSubscriberTopic) function
- [ ] Implement the function in Matrice_ROSDroneConnection

2020-07-08 19:22 UTC, erwang01 reviewed
looks good to me minor thing about switch cases.

2020-07-08 19:22 UTC, erwang01 commented on Assets/Scripts/ROS Scripts/ROS Connections v2/Drones/Matrice_ROSDroneConnection.cs
> +        Debug.LogError("Topic " + topic + " not registered.");
you can put this as a default case within the switch statement.

2020-07-08 19:23 UTC, erwang01 approved these changes

2020-07-08 19:25 UTC, erwang01 requested changes
actually sorry did Peru's comments about finding game objects not unique get addressed?

2020-07-14 03:17 UTC, orrblue commented
Reviewers, specifically @PeruDayani can you make sure I have the right version of the code in ROSManager? I copied it from master because I seemed to have the old version where a lot of stuff was commented out.

2020-07-14 17:56 UTC, PeruDayani approved these changes
Awesomeeeeee

2020-07-14 19:15 UTC, erwang01 approved these changes
looks good

2020-07-14 19:15 UTC, merged